del /s /q lib\Prism.Server.HTML.o
del /s /q lib\Prism.Server.HTML.ppu
del /s /q lib\Prism.Server.HTML.lfm
del /s /q lib\Prism.Server.Functions.o
del /s /q lib\Prism.Server.Functions.ppu
del /s /q lib\Prism.Server.Functions.lfm
del /s /q lib\Prism.BaseClass.o
del /s /q lib\Prism.BaseClass.ppu
del /s /q lib\Prism.BaseClass.lfm
