program Servidor;

uses
  System.StartUpCopy,
  FMX.Forms,
  uPrincipal in 'uPrincipal.pas' {frmPrincipal},
  uConfig in 'uConfig.pas' {frmConfiguracoes},
  uFancyDialog in '..\..\..\Classes\99 Coders\Versao 11\uFancyDialog.pas',
  uDm_Lanchonete in 'uDm_Lanchonete.pas' {DM_Lanchonete: TDataModule},
  uModel.Usuario in 'Modelo de Dados\uModel.Usuario.pas',
  uLoading in '..\..\..\Classes\99 Coders\Versao 11\uLoading.pas',
  uRota.Auth in 'Rotas\uRota.Auth.pas',
  uRota.Usuario in 'Rotas\uRota.Usuario.pas',
  uFuncoes in 'Units\uFuncoes.pas',
  uModel.Fornecedor in 'Modelo de Dados\uModel.Fornecedor.pas',
  uRota.Fornecedores in 'Rotas\uRota.Fornecedores.pas',
  uModel.Cliente in 'Modelo de Dados\uModel.Cliente.pas',
  uRota.Clientes in 'Rotas\uRota.Clientes.pas',
  uModel.Impressao in 'Modelo de Dados\uModel.Impressao.pas',
  uCriarEstrutura in '..\..\..\Global\uCriarEstrutura.pas' {frmCriarEstrutura},
  uModel.IMPRESSORAS in 'Modelo de Dados\uModel.IMPRESSORAS.pas',
  uRota.IMPRESSORAS in 'Rotas\uRota.IMPRESSORAS.pas',
  uModel.SETOR in 'Modelo de Dados\uModel.SETOR.pas',
  uRota.SETOR in 'Rotas\uRota.SETOR.pas',
  uModel.EMPRESA in 'Modelo de Dados\uModel.EMPRESA.pas',
  uRota.EMPRESA in 'Rotas\uRota.EMPRESA.pas',
  uRota.EMPRESA_ENDERECO in 'Rotas\uRota.EMPRESA_ENDERECO.pas',
  uModel.EMPRESA_ENDERECO in 'Modelo de Dados\uModel.EMPRESA_ENDERECO.pas',
  uRota.EMPRESA_TELEFONES in 'Rotas\uRota.EMPRESA_TELEFONES.pas',
  uModel.EMPRESA_TELEFONES in 'Modelo de Dados\uModel.EMPRESA_TELEFONES.pas',
  uRota.IMPRESSORA_SETOR in 'Rotas\uRota.IMPRESSORA_SETOR.pas',
  uModel.IMPRESSORA_SETOR in 'Modelo de Dados\uModel.IMPRESSORA_SETOR.pas',
  uModel.GRUPO in 'Modelo de Dados\uModel.GRUPO.pas',
  uModel.SUB_GRUPO in 'Modelo de Dados\uModel.SUB_GRUPO.pas',
  uRota.GRUPO in 'Rotas\uRota.GRUPO.pas',
  uRota.SUB_GRUPO in 'Rotas\uRota.SUB_GRUPO.pas',
  uRota.PAISES in 'Rotas\uRota.PAISES.pas',
  uModel.PAISES in 'Modelo de Dados\uModel.PAISES.pas',
  uModel.MUNICIPIOS in 'Modelo de Dados\uModel.MUNICIPIOS.pas',
  uModel.UNIDADE_FEDERATIVA in 'Modelo de Dados\uModel.UNIDADE_FEDERATIVA.pas',
  uModel.REGIOES in 'Modelo de Dados\uModel.REGIOES.pas',
  uRota.MUNICIPIOS in 'Rotas\uRota.MUNICIPIOS.pas',
  uRota.UNIDADE_FEDERATIVA in 'Rotas\uRota.UNIDADE_FEDERATIVA.pas',
  uRota.REGIOES in 'Rotas\uRota.REGIOES.pas',
  uModel.UNIDADE in 'Modelo de Dados\uModel.UNIDADE.pas',
  uRota.UNIDADE in 'Rotas\uRota.UNIDADE.pas',
  uModel.PRODUTO in 'Modelo de Dados\uModel.PRODUTO.pas',
  uRota.PRODUTO in 'Rotas\uRota.PRODUTO.pas',
  uModel.FORMA_PAGAMENTO in 'Modelo de Dados\uModel.FORMA_PAGAMENTO.pas',
  uModel.FORMA_CONDICAO_PAGAMENTO in 'Modelo de Dados\uModel.FORMA_CONDICAO_PAGAMENTO.pas',
  uModel.CONDICAO_PAGAMENTO_PARCELA in 'Modelo de Dados\uModel.CONDICAO_PAGAMENTO_PARCELA.pas',
  uModel.CONDICAO_PAGAMENTO in 'Modelo de Dados\uModel.CONDICAO_PAGAMENTO.pas',
  uRota.FORMA_PAGAMENTO in 'Rotas\uRota.FORMA_PAGAMENTO.pas',
  uRota.FORMA_CONDICAO_PAGAMENTO in 'Rotas\uRota.FORMA_CONDICAO_PAGAMENTO.pas',
  uRota.CONDICAO_PAGAMENTO_PARCELA in 'Rotas\uRota.CONDICAO_PAGAMENTO_PARCELA.pas',
  uRota.CONDICAO_PAGAMENTO in 'Rotas\uRota.CONDICAO_PAGAMENTO.pas',
  uModel.VENDA_PARCELAS in 'Modelo de Dados\uModel.VENDA_PARCELAS.pas',
  uModel.VENDA in 'Modelo de Dados\uModel.VENDA.pas',
  uModel.COMPRA_PARCELAS in 'Modelo de Dados\uModel.COMPRA_PARCELAS.pas',
  uModel.COMPRA in 'Modelo de Dados\uModel.COMPRA.pas',
  uModel.CAIXA in 'Modelo de Dados\uModel.CAIXA.pas',
  uRota.VENDA_PARCELAS in 'Rotas\uRota.VENDA_PARCELAS.pas',
  uRota.VENDA in 'Rotas\uRota.VENDA.pas',
  uRota.COMPRA_PARCELAS in 'Rotas\uRota.COMPRA_PARCELAS.pas',
  uRota.COMPRA in 'Rotas\uRota.COMPRA.pas',
  uRota.CAIXA in 'Rotas\uRota.CAIXA.pas',
  uModel.FUNCIONARIO_TELEFONES in 'Modelo de Dados\uModel.FUNCIONARIO_TELEFONES.pas',
  uModel.FUNCIONARIO_ENDERECO in 'Modelo de Dados\uModel.FUNCIONARIO_ENDERECO.pas',
  uModel.FUNCIONARIO in 'Modelo de Dados\uModel.FUNCIONARIO.pas',
  uRota.FUNCIONARIO_TELEFONES in 'Rotas\uRota.FUNCIONARIO_TELEFONES.pas',
  uRota.FUNCIONARIO_ENDERECO in 'Rotas\uRota.FUNCIONARIO_ENDERECO.pas',
  uRota.FUNCIONARIO in 'Rotas\uRota.FUNCIONARIO.pas',
  uModel.FORNECEDOR_EMAIL in 'Modelo de Dados\uModel.FORNECEDOR_EMAIL.pas',
  uModel.EMPRESA_EMAIL in 'Modelo de Dados\uModel.EMPRESA_EMAIL.pas',
  uModel.CLIENTE_EMAIL in 'Modelo de Dados\uModel.CLIENTE_EMAIL.pas',
  uRota.FORNECEDOR_EMAIL in 'Rotas\uRota.FORNECEDOR_EMAIL.pas',
  uRota.EMPRESA_EMAIL in 'Rotas\uRota.EMPRESA_EMAIL.pas',
  uRota.CLIENTE_EMAIL in 'Rotas\uRota.CLIENTE_EMAIL.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TDM_Lanchonete, DM_Lanchonete);
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.Run;
end.
